---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: '{{ .Values.global.namespace }}-{{ .Values.label }}'
    namespace: {{ .Values.global.namespace }}
    labels:
        app: {{ .Values.label }}
    annotations:
        # TODO: update the role-arn below to be unique for each micro-service and environment
        #eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789101:role/{{ .Values.global.namespace }}-{{ .Values.label }}'
        eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789101:role/api-service-account-role-{{ .Values.global.namespace }}'
automountServiceAccountToken: true
