name: Auto Increment and Deploy Helm Chart to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install yq
      #   run: |
      #     sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.12.2/yq_linux_amd64
      #     sudo chmod +x /usr/local/bin/yq

      # - name: Increment Chart Version
      #   run: |
      #     CURRENT_VERSION=$(yq e '.version' ./charts/Chart.yaml)
      #     NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
      #     yq eval -i ".version = \"$NEW_VERSION\"" ./charts/Chart.yaml

      # - name: Configure Git
      #   run: |
      #     git config user.name "bots"
      #     git config user.email "tech+bots@devopsidiot.com"

      # - name: Push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/devopsidiot/helm.git
      #     git push origin main

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        run: helm package ./charts

      - name: Upload Helm Chart to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws s3 cp world-eater-*.tgz s3://devopsidiot-helm

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
